# Install Active Directory Domain services
- name: install Active Directory Domain services
  win_feature:
    name: AD-Domain-Services
    include_management_tools: yes
    include_sub_features: yes
    state: present
  register: installed_result

    
